name: Publish apk

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Build and publish apk
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Check out the repo
        uses: actions/checkout@v5.0.1

      - name: Setup JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build app
        run: ./gradlew --no-daemon assembleRelease

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@2.11.2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref }}
          file: ./app/build/outputs/apk/release/app-release.apk
          asset_name: FavoritesImmortalizer-$tag.apk
